### ISSUE TITLE
Cube not rotating

### ISSUE THREAD

**Issue by ZahraaBass** [Unity-Technologies/Robotics-Object-Pose-Estimation#11]
Hello, thank you for the very beneficial tutorial, I'm currently going through it. 
In part 2, I've followed the tutorial up to step 10 without errors. In step 10, the cube is overlaid with a green bounding box, however, it is not rotating. Any idea what could be the problem? I'm using Unity 2020.2.0f1

The following is a screenshot of my editor.
<img width="1721" alt="Screen Shot 2021-03-02 at 10 18 32 AM" src="https://user-images.githubusercontent.com/76676384/109618788-a584cf80-7b40-11eb-9b8c-755e0d397e62.png">

and if i continue to step 11, same thing, the box moves to a place and then stops moving, like the photo attached:

<img width="832" alt="Screen Shot 2021-03-02 at 10 37 34 AM" src="https://user-images.githubusercontent.com/76676384/109621092-4d9b9800-7b43-11eb-85c5-46dc318207ef.png">

**Comment by at669** [comment]
Hi @ZahraaBass! You most likely need to enable the "Automatic Iteration" box in the Pose Estimation Scenario script. Thanks for catching this! We'll add it to the instructions.

![Screen Shot 2021-03-02 at 9 19 38 AM](https://user-images.githubusercontent.com/31416491/109679387-c517fa00-7b38-11eb-84e9-5c18debe9605.png)

**Comment by ZahraaBass** [comment]
Perfect! 
@at669 Thank you so much! Works fine now :)

**Comment by ZahraaBass** [comment]
Hello @at669, I have another question please.

I've reached step 2 in Part3: (set the Total Iterations field under Constants to 30000), however, in my inspector window, this field is not showing:

<img width="1548" alt="Screen Shot 2021-03-03 at 8 34 06 AM" src="https://user-images.githubusercontent.com/76676384/109763942-8d25bb00-7bfb-11eb-80f9-fb9635e8cd23.png">

is it the same as the totalFrames constant? and can I set it in the code instead?

**Comment by at669** [comment]
Yes, this is the same as `totalFrames`! You are able to set it in the code for the same behavior; however, if you would like to expose it in the Inspector window for ease of use, you may add the `Serializable` attribute to the PoseEstimationScenarioConstants, i.e.:

```csharp
[System.Serializable]
public class PoseEstimationScenarioConstants : ScenarioConstants
{
    public int totalFrames = 1000;
}
```

We will also clarify this in the tutorial. Thanks for trying it out!

**Comment by ZahraaBass** [comment]
OKay great!! @at669 Btw thank you so much for the very detailed tutorial :D
