### ISSUE TITLE
Broken gripper with TGS physics solver

### ISSUE THREAD

**Issue by mathujeyanth** [Unity-Technologies/Robotics-Object-Pose-Estimation#19]
Hi, I have been testing the project and encountered that the gripper "broke" when using the improved Temporal Gauss Seidel (TGS) physics solver with it. Here is a repro of the problem, where I open the pre-made project and change the solver from Projected GS to TGS:

![TGS](https://user-images.githubusercontent.com/40917493/109953773-c7b55380-7ce0-11eb-995d-950ac31d70d0.gif)

**Comment by mrpropellers** [comment]
Hey Jeyanth!  This is a known limitation of this project at the moment, and we are still in the process of investigating it internally. Do you have a use case that requires the TGS solver?  If so, let me know, and that will help us prioritize this bug in our queue!

**Comment by mrpropellers** [comment]
Since this is a known issue I'm going to go ahead and close this ticket.  @mathujeyanth, feel free to follow up with robotics@unity3d.com if you have specific requirements that mandate using the TGS solver; we love to hear about customer use cases!
