### ISSUE TITLE
Not compatible with latest perception sdk build 0.8.0-preview.3

### ISSUE THREAD

**Issue by arunabaijal** [Unity-Technologies/Robotics-Object-Pose-Estimation#24]
While importing scene, PoseEstimationScenario.cs has errors:
    1. Assets/TutorialAssets/Scripts/PoseEstimationScenario.cs(27,26): error CS0507: 'PoseEstimationScenario.isIterationComplete': cannot change access modifiers when overriding 'protected' inherited member 'ScenarioBase.isIterationComplete'
    2. Assets/TutorialAssets/Scripts/PoseEstimationScenario.cs(28,26): error CS0507: 'PoseEstimationScenario.isScenarioComplete': cannot change access modifiers when overriding 'protected' inherited member 'ScenarioBase.isScenarioComplete'
    3. Assets/TutorialAssets/Scripts/PoseEstimationScenario.cs(10,14): error CS0534: 'PoseEstimationScenario' does not implement inherited abstract member 'ScenarioBase.isScenarioReadyToStart.get'

Modified the file to fix these errors and generated data. Noticed that metrics.json are not being created only captures.json are. When starting training, it gives an error in between looking for metrics data. Had to revert back 0.7.0-preview.2 build to regenerate data for training.

Can this be updated to be compatible with perception 0.8.0-preview.3 (or the latest) build. It is suspected that the previous builds had some bug in them which gave erroneous bounding box data which led to poor training results for pose estimation.

**Comment by sleal-unity** [comment]
Hi @arunabaijal,

Thanks for bringing these issues to our attention. I've got a PR in review now that will update the demo project to perception 0.8.0-preview.3 and address all of these issues.

I'll ping you again in this issues thread once the fix gets pushed to master so you can pull it down on your side.

**Comment by arunabaijal** [comment]
Thanks @sleal-unity ! One more point I forgot to mention, when generating images I mention the total number in Simulation Scenario under Pose Estimation Scenario script (Total frames). The randomization runs till those many frames are generated but after that the scene continues playing with the last randomized configuration and keeps generating images till I manually stop the scene. This wasn't happening with the previous build where the scene would terminate on its own after generating required number of images.

**Comment by sleal-unity** [comment]
Good catch! Yep, in 0.8.0 of perception, the base scenario class used to create the custom scenario in the demo project had most of the Perception-specific logic abstracted into a derived class called PerceptionScenario. In the PR I submitted, the custom scenario in the demo project now derives from PerceptionScenario to get that "quit on complete" behavior back.

**Comment by sleal-unity** [comment]
@arunabaijal The update to perception 0.8.0 has been merged. Feel free to open a new ticket to let us know if you run into any problems.

**Comment by arunabaijal** [comment]
Thanks a lot for your help @sleal-unity ! Apologies for not getting back sooner. Just one final question, the training on my personal GPU is going very slow, I was hoping to shift to multiple GPUs using AWS, is this compatible with multi-GPU systems?

**Comment by sleal-unity** [comment]
Hi again @arunabaijal! Quick clarification, are you asking about training in the cloud or synthetic data generation?

**Comment by arunabaijal** [comment]
Training with existing perception data on a multi-gpu system

**Comment by sarahwolf32** [comment]
Hello @arunabaijal, unfortunately, the model does not support multi-gpu training. However, feel free to modify the code to suit your needs - it is implemented in PyTorch.

**Comment by hygradme** [comment]
So I still encountered the exact same errors as https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/issues/24#issue-851618305 by installing "com.unity.perception@0.8.0-preview.3" at Package Manager following the tutorial.
Have the issue not been fixed yet?

**Comment by at669** [comment]
Hi @hygradme, this was resolved in #25. Please make sure you have pulled the latest updates to the `main` branch!

**Comment by hygradme** [comment]
@at669 
I now realized that the Tutorial Asset obtained from  the link "TutorialAsset.zip" in  https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/Documentation/1_set_up_the_scene.md#adding-tutorial-files is not updated yet.

Since I just read the tutorial and follow the instruction, I didn't use the updated TutorialAsset in the main repository.
By just replacing the TutorialAsset with the new one, these errors disappear. Thanks.

**Comment by at669** [comment]
@hygradme, great to hear it's resolved! I will be closing out this ticket.

@arunabaijal, feel free to open a new ticket if you would like more support on a new issue. Thanks!
