### ISSUE TITLE
How to add custom messages to the ROS-Unity communication

### ISSUE THREAD

**Issue by tensarflow** [Unity-Technologies/Robotics-Object-Pose-Estimation#46]
It would be great if you could briefly show us how to add custom ROS messages to the system. For example I'm trying to stream camera images from Unity to ROS.

**Comment by at669** [comment]
Hi, thanks for checking out the Object Pose Estimation demo!

For steps on adding custom ROS messages, you can check out our other resources on using our tools:

- The [Pick-and-Place](https://github.com/Unity-Technologies/Unity-Robotics-Hub/tree/main/tutorials/pick_and_place) tutorial contains end-to-end instructions on ROS integration with Unity, including [Generating the C# scripts for custom messages](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/2_ros_tcp.md#the-unity-side).
- The [ROS–Unity Demo Setup](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/setup.md) includes the minimum requirements for a ROS–Unity integration, and the setup for the Unity Robotics Demo package, which you will need if you're following the ROS–Unity Integration tutorials--which also contains details on how to generate C# scripts for custom messages.

For streaming camera images, you can use the ROS connection to receive and interpret textures or other data from your camera. There are existing utilities you can utilize:
- You can use the [Visualizations Package](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/main/com.unity.robotics.visualizations/Documentation~/README.md) for out-of-the-box sensor_msgs/Image or /CompressedImage support.
- [`ToTexture2D()`](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/7f055108f43ab11ff297175a52af5d30fbac9d57/com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/MessageExtensions.cs#L559-L578) can convert a ROS image message into a Unity texture for you.

Hope this helps!

**Comment by Hasan-atc** [comment]
I cannot visualize the data coming from the Unity camera with the methods you describe. Can you help me?

**Comment by Hasan-atc** [comment]
I added the Visualizations Package system you specified to unity, but I can't find a button to visualize the frames when the robotic arm is moving in the HUD window. In short, I cannot view the streaming camera footage. Could you help?

**Comment by at669** [comment]
@Hasan-atc, as this appears to be a visualizations-specific issue, could you post a new ticket in the ROS-TCP-Connector repo with the [Bug Report Template](https://github.com/Unity-Technologies/ROS-TCP-Connector/issues/new?assignees=&labels=&template=bug_report.md&title=)? In it, please clarify the status of your ROS Connection as well.

I will close this ticket with regards to the custom ROS messages, as that has been resolved. Thanks!
