### ISSUE TITLE
Resume Training

### ISSUE THREAD

**Issue by agru97** [Unity-Technologies/Robotics-Object-Pose-Estimation#48]
How can I resume training when it got stopped during the process?

**Comment by at669** [comment]
Initializing a `PoseEstimationEstimator` will try to load the estimators from file if a `checkpoint_file` exists: https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/7558d74b21f6e22544138c5b5f8525f24ff60c98/Model/pose_estimation/pose_estimation_estimator.py#L69-L72 which calls `load()`: https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/7558d74b21f6e22544138c5b5f8525f24ff60c98/Model/pose_estimation/pose_estimation_estimator.py#L103-L123

Or, if you're using Docker, you may investigate using [checkpoints](https://docs.docker.com/engine/reference/commandline/checkpoint/). 

Hope this helps!
