### ISSUE TITLE
More complex 3D models

### ISSUE THREAD

**Issue by AnnaMelk** [Unity-Technologies/Robotics-Object-Pose-Estimation#61]
Hello, I would like to know if this model can work well on complex shapes and models. And would maybe I need some changes in data generation process for training, like having images from different camera positions?

And thank you for the project and extensive tutorial!

**Comment by JonathanLeban** [comment]
Hello AnnaMelk, thank you for your question. The model should work on complex shapes and models for **single object**. In fact, the architecture of the model is very simple (VGG16) so there are some limitations in term of the complexity of the problem you want to solve but that should work for single object. If that doesn't work, you can still add few convolutional layers to the existing model (before the dense layers, so [here](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/Model/pose_estimation/model.py#L29). Also, when you generate the data you should randomize the camera positions. Do you have occlusions in your environment (part of the target object hidden by other objects)? 
I hope it answers your question and let us know if you have some troubles to solve your problem. 

Thank you for your comment, we really appreciate it.
